// Code generated by entc, DO NOT EDIT.

package course

const (
	// Label holds the string label denoting the course type in the database.
	Label = "course"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCourseName holds the string denoting the course_name field in the database.
	FieldCourseName = "course_name"

	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeCourseItems holds the string denoting the course_items edge name in mutations.
	EdgeCourseItems = "course_items"

	// Table holds the table name of the course in the database.
	Table = "courses"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "courses"
	// OwnerInverseTable is the table name for the Teacher entity.
	// It exists in this package in order to avoid circular dependency with the "teacher" package.
	OwnerInverseTable = "teachers"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
	// CourseItemsTable is the table the holds the course_items relation/edge.
	CourseItemsTable = "course_items"
	// CourseItemsInverseTable is the table name for the CourseItem entity.
	// It exists in this package in order to avoid circular dependency with the "courseitem" package.
	CourseItemsInverseTable = "course_items"
	// CourseItemsColumn is the table column denoting the course_items relation/edge.
	CourseItemsColumn = "course_id"
)

// Columns holds all SQL columns for course fields.
var Columns = []string{
	FieldID,
	FieldCourseName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Course type.
var ForeignKeys = []string{
	"owner_id",
}

var (
	// CourseNameValidator is a validator for the "course_name" field. It is called by the builders before save.
	CourseNameValidator func(string) error
)
