// Code generated by entc, DO NOT EDIT.

package subject

const (
	// Label holds the string label denoting the subject type in the database.
	Label = "subject"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubjectName holds the string denoting the subject_name field in the database.
	FieldSubjectName = "subject_name"

	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeCourseItems holds the string denoting the course_items edge name in mutations.
	EdgeCourseItems = "course_items"

	// Table holds the table name of the subject in the database.
	Table = "subjects"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "subjects"
	// OwnerInverseTable is the table name for the Teacher entity.
	// It exists in this package in order to avoid circular dependency with the "teacher" package.
	OwnerInverseTable = "teachers"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
	// CourseItemsTable is the table the holds the course_items relation/edge.
	CourseItemsTable = "course_items"
	// CourseItemsInverseTable is the table name for the CourseItem entity.
	// It exists in this package in order to avoid circular dependency with the "courseitem" package.
	CourseItemsInverseTable = "course_items"
	// CourseItemsColumn is the table column denoting the course_items relation/edge.
	CourseItemsColumn = "subject_id"
)

// Columns holds all SQL columns for subject fields.
var Columns = []string{
	FieldID,
	FieldSubjectName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Subject type.
var ForeignKeys = []string{
	"owner_id",
}

var (
	// SubjectNameValidator is a validator for the "subject_name" field. It is called by the builders before save.
	SubjectNameValidator func(string) error
)
