// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// CourseItem is the predicate function for courseitem builders.
type CourseItem func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)

// SubjectType is the predicate function for subjecttype builders.
type SubjectType func(*sql.Selector)

// Teacher is the predicate function for teacher builders.
type Teacher func(*sql.Selector)
