// Code generated by entc, DO NOT EDIT.

package subjecttype

const (
	// Label holds the string label denoting the subjecttype type in the database.
	Label = "subject_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTypeName holds the string denoting the type_name field in the database.
	FieldTypeName = "type_name"

	// EdgeCourseItems holds the string denoting the course_items edge name in mutations.
	EdgeCourseItems = "course_items"

	// Table holds the table name of the subjecttype in the database.
	Table = "subject_types"
	// CourseItemsTable is the table the holds the course_items relation/edge.
	CourseItemsTable = "course_items"
	// CourseItemsInverseTable is the table name for the CourseItem entity.
	// It exists in this package in order to avoid circular dependency with the "courseitem" package.
	CourseItemsInverseTable = "course_items"
	// CourseItemsColumn is the table column denoting the course_items relation/edge.
	CourseItemsColumn = "type_id"
)

// Columns holds all SQL columns for subjecttype fields.
var Columns = []string{
	FieldID,
	FieldTypeName,
}

var (
	// TypeNameValidator is a validator for the "type_name" field. It is called by the builders before save.
	TypeNameValidator func(string) error
)
