// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/ACER/app/ent/course"
	"github.com/ACER/app/ent/teacher"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Course is the model entity for the Course schema.
type Course struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CourseName holds the value of the "course_name" field.
	CourseName string `json:"course_name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CourseQuery when eager-loading is set.
	Edges    CourseEdges `json:"edges"`
	owner_id *int
}

// CourseEdges holds the relations/edges for other nodes in the graph.
type CourseEdges struct {
	// Owner holds the value of the owner edge.
	Owner *Teacher
	// CourseItems holds the value of the course_items edge.
	CourseItems []*CourseItem
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CourseEdges) OwnerOrErr() (*Teacher, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// The edge owner was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: teacher.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// CourseItemsOrErr returns the CourseItems value or an error if the edge
// was not loaded in eager-loading.
func (e CourseEdges) CourseItemsOrErr() ([]*CourseItem, error) {
	if e.loadedTypes[1] {
		return e.CourseItems, nil
	}
	return nil, &NotLoadedError{edge: "course_items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Course) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // course_name
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Course) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // owner_id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Course fields.
func (c *Course) assignValues(values ...interface{}) error {
	if m, n := len(values), len(course.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	c.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field course_name", values[0])
	} else if value.Valid {
		c.CourseName = value.String
	}
	values = values[1:]
	if len(values) == len(course.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field owner_id", value)
		} else if value.Valid {
			c.owner_id = new(int)
			*c.owner_id = int(value.Int64)
		}
	}
	return nil
}

// QueryOwner queries the owner edge of the Course.
func (c *Course) QueryOwner() *TeacherQuery {
	return (&CourseClient{config: c.config}).QueryOwner(c)
}

// QueryCourseItems queries the course_items edge of the Course.
func (c *Course) QueryCourseItems() *CourseItemQuery {
	return (&CourseClient{config: c.config}).QueryCourseItems(c)
}

// Update returns a builder for updating this Course.
// Note that, you need to call Course.Unwrap() before calling this method, if this Course
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Course) Update() *CourseUpdateOne {
	return (&CourseClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (c *Course) Unwrap() *Course {
	tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Course is not a transactional entity")
	}
	c.config.driver = tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Course) String() string {
	var builder strings.Builder
	builder.WriteString("Course(")
	builder.WriteString(fmt.Sprintf("id=%v", c.ID))
	builder.WriteString(", course_name=")
	builder.WriteString(c.CourseName)
	builder.WriteByte(')')
	return builder.String()
}

// Courses is a parsable slice of Course.
type Courses []*Course

func (c Courses) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
