// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/ACER/app/ent/course"
	"github.com/ACER/app/ent/schema"
	"github.com/ACER/app/ent/subject"
	"github.com/ACER/app/ent/subjecttype"
	"github.com/ACER/app/ent/teacher"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	courseFields := schema.Course{}.Fields()
	_ = courseFields
	// courseDescCourseName is the schema descriptor for course_name field.
	courseDescCourseName := courseFields[0].Descriptor()
	// course.CourseNameValidator is a validator for the "course_name" field. It is called by the builders before save.
	course.CourseNameValidator = courseDescCourseName.Validators[0].(func(string) error)
	subjectFields := schema.Subject{}.Fields()
	_ = subjectFields
	// subjectDescSubjectName is the schema descriptor for subject_name field.
	subjectDescSubjectName := subjectFields[0].Descriptor()
	// subject.SubjectNameValidator is a validator for the "subject_name" field. It is called by the builders before save.
	subject.SubjectNameValidator = subjectDescSubjectName.Validators[0].(func(string) error)
	subjecttypeFields := schema.SubjectType{}.Fields()
	_ = subjecttypeFields
	// subjecttypeDescTypeName is the schema descriptor for type_name field.
	subjecttypeDescTypeName := subjecttypeFields[0].Descriptor()
	// subjecttype.TypeNameValidator is a validator for the "type_name" field. It is called by the builders before save.
	subjecttype.TypeNameValidator = subjecttypeDescTypeName.Validators[0].(func(string) error)
	teacherFields := schema.Teacher{}.Fields()
	_ = teacherFields
	// teacherDescTeacherEmail is the schema descriptor for teacher_email field.
	teacherDescTeacherEmail := teacherFields[0].Descriptor()
	// teacher.TeacherEmailValidator is a validator for the "teacher_email" field. It is called by the builders before save.
	teacher.TeacherEmailValidator = teacherDescTeacherEmail.Validators[0].(func(string) error)
	// teacherDescTeacherName is the schema descriptor for teacher_name field.
	teacherDescTeacherName := teacherFields[1].Descriptor()
	// teacher.TeacherNameValidator is a validator for the "teacher_name" field. It is called by the builders before save.
	teacher.TeacherNameValidator = teacherDescTeacherName.Validators[0].(func(string) error)
}
