// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/ACER/app/ent/courseitem"
	"github.com/ACER/app/ent/subjecttype"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// SubjectTypeCreate is the builder for creating a SubjectType entity.
type SubjectTypeCreate struct {
	config
	mutation *SubjectTypeMutation
	hooks    []Hook
}

// SetTypeName sets the type_name field.
func (stc *SubjectTypeCreate) SetTypeName(s string) *SubjectTypeCreate {
	stc.mutation.SetTypeName(s)
	return stc
}

// AddCourseItemIDs adds the course_items edge to CourseItem by ids.
func (stc *SubjectTypeCreate) AddCourseItemIDs(ids ...int) *SubjectTypeCreate {
	stc.mutation.AddCourseItemIDs(ids...)
	return stc
}

// AddCourseItems adds the course_items edges to CourseItem.
func (stc *SubjectTypeCreate) AddCourseItems(c ...*CourseItem) *SubjectTypeCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return stc.AddCourseItemIDs(ids...)
}

// Mutation returns the SubjectTypeMutation object of the builder.
func (stc *SubjectTypeCreate) Mutation() *SubjectTypeMutation {
	return stc.mutation
}

// Save creates the SubjectType in the database.
func (stc *SubjectTypeCreate) Save(ctx context.Context) (*SubjectType, error) {
	if _, ok := stc.mutation.TypeName(); !ok {
		return nil, &ValidationError{Name: "type_name", err: errors.New("ent: missing required field \"type_name\"")}
	}
	if v, ok := stc.mutation.TypeName(); ok {
		if err := subjecttype.TypeNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "type_name", err: fmt.Errorf("ent: validator failed for field \"type_name\": %w", err)}
		}
	}
	var (
		err  error
		node *SubjectType
	)
	if len(stc.hooks) == 0 {
		node, err = stc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SubjectTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			stc.mutation = mutation
			node, err = stc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(stc.hooks) - 1; i >= 0; i-- {
			mut = stc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, stc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (stc *SubjectTypeCreate) SaveX(ctx context.Context) *SubjectType {
	v, err := stc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (stc *SubjectTypeCreate) sqlSave(ctx context.Context) (*SubjectType, error) {
	st, _spec := stc.createSpec()
	if err := sqlgraph.CreateNode(ctx, stc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	st.ID = int(id)
	return st, nil
}

func (stc *SubjectTypeCreate) createSpec() (*SubjectType, *sqlgraph.CreateSpec) {
	var (
		st    = &SubjectType{config: stc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: subjecttype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: subjecttype.FieldID,
			},
		}
	)
	if value, ok := stc.mutation.TypeName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: subjecttype.FieldTypeName,
		})
		st.TypeName = value
	}
	if nodes := stc.mutation.CourseItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subjecttype.CourseItemsTable,
			Columns: []string{subjecttype.CourseItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: courseitem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return st, _spec
}
