// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/ACER/app/ent/course"
	"github.com/ACER/app/ent/subject"
	"github.com/ACER/app/ent/teacher"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// TeacherCreate is the builder for creating a Teacher entity.
type TeacherCreate struct {
	config
	mutation *TeacherMutation
	hooks    []Hook
}

// SetTeacherEmail sets the teacher_email field.
func (tc *TeacherCreate) SetTeacherEmail(s string) *TeacherCreate {
	tc.mutation.SetTeacherEmail(s)
	return tc
}

// SetTeacherName sets the teacher_name field.
func (tc *TeacherCreate) SetTeacherName(s string) *TeacherCreate {
	tc.mutation.SetTeacherName(s)
	return tc
}

// AddSubjectIDs adds the subjects edge to Subject by ids.
func (tc *TeacherCreate) AddSubjectIDs(ids ...int) *TeacherCreate {
	tc.mutation.AddSubjectIDs(ids...)
	return tc
}

// AddSubjects adds the subjects edges to Subject.
func (tc *TeacherCreate) AddSubjects(s ...*Subject) *TeacherCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tc.AddSubjectIDs(ids...)
}

// AddCourseIDs adds the courses edge to Course by ids.
func (tc *TeacherCreate) AddCourseIDs(ids ...int) *TeacherCreate {
	tc.mutation.AddCourseIDs(ids...)
	return tc
}

// AddCourses adds the courses edges to Course.
func (tc *TeacherCreate) AddCourses(c ...*Course) *TeacherCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return tc.AddCourseIDs(ids...)
}

// Mutation returns the TeacherMutation object of the builder.
func (tc *TeacherCreate) Mutation() *TeacherMutation {
	return tc.mutation
}

// Save creates the Teacher in the database.
func (tc *TeacherCreate) Save(ctx context.Context) (*Teacher, error) {
	if _, ok := tc.mutation.TeacherEmail(); !ok {
		return nil, &ValidationError{Name: "teacher_email", err: errors.New("ent: missing required field \"teacher_email\"")}
	}
	if v, ok := tc.mutation.TeacherEmail(); ok {
		if err := teacher.TeacherEmailValidator(v); err != nil {
			return nil, &ValidationError{Name: "teacher_email", err: fmt.Errorf("ent: validator failed for field \"teacher_email\": %w", err)}
		}
	}
	if _, ok := tc.mutation.TeacherName(); !ok {
		return nil, &ValidationError{Name: "teacher_name", err: errors.New("ent: missing required field \"teacher_name\"")}
	}
	if v, ok := tc.mutation.TeacherName(); ok {
		if err := teacher.TeacherNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "teacher_name", err: fmt.Errorf("ent: validator failed for field \"teacher_name\": %w", err)}
		}
	}
	var (
		err  error
		node *Teacher
	)
	if len(tc.hooks) == 0 {
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TeacherMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tc.mutation = mutation
			node, err = tc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TeacherCreate) SaveX(ctx context.Context) *Teacher {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tc *TeacherCreate) sqlSave(ctx context.Context) (*Teacher, error) {
	t, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	t.ID = int(id)
	return t, nil
}

func (tc *TeacherCreate) createSpec() (*Teacher, *sqlgraph.CreateSpec) {
	var (
		t     = &Teacher{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: teacher.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: teacher.FieldID,
			},
		}
	)
	if value, ok := tc.mutation.TeacherEmail(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: teacher.FieldTeacherEmail,
		})
		t.TeacherEmail = value
	}
	if value, ok := tc.mutation.TeacherName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: teacher.FieldTeacherName,
		})
		t.TeacherName = value
	}
	if nodes := tc.mutation.SubjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teacher.SubjectsTable,
			Columns: []string{teacher.SubjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subject.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teacher.CoursesTable,
			Columns: []string{teacher.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: course.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return t, _spec
}
