// Code generated by entc, DO NOT EDIT.

package courseitem

const (
	// Label holds the string label denoting the courseitem type in the database.
	Label = "course_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeCourses holds the string denoting the courses edge name in mutations.
	EdgeCourses = "courses"
	// EdgeSubjects holds the string denoting the subjects edge name in mutations.
	EdgeSubjects = "subjects"
	// EdgeTypes holds the string denoting the types edge name in mutations.
	EdgeTypes = "types"

	// Table holds the table name of the courseitem in the database.
	Table = "course_items"
	// CoursesTable is the table the holds the courses relation/edge.
	CoursesTable = "course_items"
	// CoursesInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	CoursesInverseTable = "courses"
	// CoursesColumn is the table column denoting the courses relation/edge.
	CoursesColumn = "course_id"
	// SubjectsTable is the table the holds the subjects relation/edge.
	SubjectsTable = "course_items"
	// SubjectsInverseTable is the table name for the Subject entity.
	// It exists in this package in order to avoid circular dependency with the "subject" package.
	SubjectsInverseTable = "subjects"
	// SubjectsColumn is the table column denoting the subjects relation/edge.
	SubjectsColumn = "subject_id"
	// TypesTable is the table the holds the types relation/edge.
	TypesTable = "course_items"
	// TypesInverseTable is the table name for the SubjectType entity.
	// It exists in this package in order to avoid circular dependency with the "subjecttype" package.
	TypesInverseTable = "subject_types"
	// TypesColumn is the table column denoting the types relation/edge.
	TypesColumn = "type_id"
)

// Columns holds all SQL columns for courseitem fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the CourseItem type.
var ForeignKeys = []string{
	"course_id",
	"subject_id",
	"type_id",
}
