/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Project API Course Item
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCourseItem,
    EntCourseItemFromJSON,
    EntCourseItemFromJSONTyped,
    EntCourseItemToJSON,
    EntTeacher,
    EntTeacherFromJSON,
    EntTeacherFromJSONTyped,
    EntTeacherToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCourseEdges
 */
export interface EntCourseEdges {
    /**
     * CourseItems holds the value of the course_items edge.
     * @type {Array<EntCourseItem>}
     * @memberof EntCourseEdges
     */
    courseItems?: Array<EntCourseItem>;
    /**
     * 
     * @type {EntTeacher}
     * @memberof EntCourseEdges
     */
    owner?: EntTeacher;
}

export function EntCourseEdgesFromJSON(json: any): EntCourseEdges {
    return EntCourseEdgesFromJSONTyped(json, false);
}

export function EntCourseEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCourseEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseItems': !exists(json, 'courseItems') ? undefined : ((json['courseItems'] as Array<any>).map(EntCourseItemFromJSON)),
        'owner': !exists(json, 'owner') ? undefined : EntTeacherFromJSON(json['owner']),
    };
}

export function EntCourseEdgesToJSON(value?: EntCourseEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'courseItems': value.courseItems === undefined ? undefined : ((value.courseItems as Array<any>).map(EntCourseItemToJSON)),
        'owner': EntTeacherToJSON(value.owner),
    };
}


