/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Project API Course Item
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCourseEdges,
    EntCourseEdgesFromJSON,
    EntCourseEdgesFromJSONTyped,
    EntCourseEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCourse
 */
export interface EntCourse {
    /**
     * CourseName holds the value of the "course_name" field.
     * @type {string}
     * @memberof EntCourse
     */
    courseName?: string;
    /**
     * 
     * @type {EntCourseEdges}
     * @memberof EntCourse
     */
    edges?: EntCourseEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntCourse
     */
    id?: number;
}

export function EntCourseFromJSON(json: any): EntCourse {
    return EntCourseFromJSONTyped(json, false);
}

export function EntCourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCourse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseName': !exists(json, 'course_name') ? undefined : json['course_name'],
        'edges': !exists(json, 'edges') ? undefined : EntCourseEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntCourseToJSON(value?: EntCourse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'course_name': value.courseName,
        'edges': EntCourseEdgesToJSON(value.edges),
        'id': value.id,
    };
}


