/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Project API Course Item
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCourseItemEdges,
    EntCourseItemEdgesFromJSON,
    EntCourseItemEdgesFromJSONTyped,
    EntCourseItemEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCourseItem
 */
export interface EntCourseItem {
    /**
     * 
     * @type {EntCourseItemEdges}
     * @memberof EntCourseItem
     */
    edges?: EntCourseItemEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntCourseItem
     */
    id?: number;
}

export function EntCourseItemFromJSON(json: any): EntCourseItem {
    return EntCourseItemFromJSONTyped(json, false);
}

export function EntCourseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCourseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntCourseItemEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntCourseItemToJSON(value?: EntCourseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntCourseItemEdgesToJSON(value.edges),
        'id': value.id,
    };
}


