/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Project API Course Item
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCourseItem,
    EntCourseItemFromJSON,
    EntCourseItemFromJSONTyped,
    EntCourseItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntSubjectTypeEdges
 */
export interface EntSubjectTypeEdges {
    /**
     * CourseItems holds the value of the course_items edge.
     * @type {Array<EntCourseItem>}
     * @memberof EntSubjectTypeEdges
     */
    courseItems?: Array<EntCourseItem>;
}

export function EntSubjectTypeEdgesFromJSON(json: any): EntSubjectTypeEdges {
    return EntSubjectTypeEdgesFromJSONTyped(json, false);
}

export function EntSubjectTypeEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntSubjectTypeEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseItems': !exists(json, 'courseItems') ? undefined : ((json['courseItems'] as Array<any>).map(EntCourseItemFromJSON)),
    };
}

export function EntSubjectTypeEdgesToJSON(value?: EntSubjectTypeEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'courseItems': value.courseItems === undefined ? undefined : ((value.courseItems as Array<any>).map(EntCourseItemToJSON)),
    };
}


