/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Project API Course Item
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCourse,
    EntCourseFromJSON,
    EntCourseFromJSONTyped,
    EntCourseToJSON,
    EntSubject,
    EntSubjectFromJSON,
    EntSubjectFromJSONTyped,
    EntSubjectToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntTeacherEdges
 */
export interface EntTeacherEdges {
    /**
     * Courses holds the value of the courses edge.
     * @type {Array<EntCourse>}
     * @memberof EntTeacherEdges
     */
    courses?: Array<EntCourse>;
    /**
     * Subjects holds the value of the subjects edge.
     * @type {Array<EntSubject>}
     * @memberof EntTeacherEdges
     */
    subjects?: Array<EntSubject>;
}

export function EntTeacherEdgesFromJSON(json: any): EntTeacherEdges {
    return EntTeacherEdgesFromJSONTyped(json, false);
}

export function EntTeacherEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntTeacherEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courses': !exists(json, 'courses') ? undefined : ((json['courses'] as Array<any>).map(EntCourseFromJSON)),
        'subjects': !exists(json, 'subjects') ? undefined : ((json['subjects'] as Array<any>).map(EntSubjectFromJSON)),
    };
}

export function EntTeacherEdgesToJSON(value?: EntTeacherEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'courses': value.courses === undefined ? undefined : ((value.courses as Array<any>).map(EntCourseToJSON)),
        'subjects': value.subjects === undefined ? undefined : ((value.subjects as Array<any>).map(EntSubjectToJSON)),
    };
}


