// Code generated by entc, DO NOT EDIT.

package teacher

const (
	// Label holds the string label denoting the teacher type in the database.
	Label = "teacher"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTeacherEmail holds the string denoting the teacher_email field in the database.
	FieldTeacherEmail = "teacher_email"
	// FieldTeacherName holds the string denoting the teacher_name field in the database.
	FieldTeacherName = "teacher_name"

	// EdgeSubjects holds the string denoting the subjects edge name in mutations.
	EdgeSubjects = "subjects"
	// EdgeCourses holds the string denoting the courses edge name in mutations.
	EdgeCourses = "courses"

	// Table holds the table name of the teacher in the database.
	Table = "teachers"
	// SubjectsTable is the table the holds the subjects relation/edge.
	SubjectsTable = "subjects"
	// SubjectsInverseTable is the table name for the Subject entity.
	// It exists in this package in order to avoid circular dependency with the "subject" package.
	SubjectsInverseTable = "subjects"
	// SubjectsColumn is the table column denoting the subjects relation/edge.
	SubjectsColumn = "owner_id"
	// CoursesTable is the table the holds the courses relation/edge.
	CoursesTable = "courses"
	// CoursesInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	CoursesInverseTable = "courses"
	// CoursesColumn is the table column denoting the courses relation/edge.
	CoursesColumn = "owner_id"
)

// Columns holds all SQL columns for teacher fields.
var Columns = []string{
	FieldID,
	FieldTeacherEmail,
	FieldTeacherName,
}

var (
	// TeacherEmailValidator is a validator for the "teacher_email" field. It is called by the builders before save.
	TeacherEmailValidator func(string) error
	// TeacherNameValidator is a validator for the "teacher_name" field. It is called by the builders before save.
	TeacherNameValidator func(string) error
)
